spring:
  application:
    name: 4vidia-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: 4vidia-coupon-service
              uri: lb://4vidia-coupon-service
              predicates:
                - Path=/api/v1/coupon-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-user-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/user-service/auth/emails/exists
              filters:
                - StripPrefix=3
                - name: NotJwtAuthorizationHeaderFilter

            - id: 4vidia-user-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/user-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-order-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/order-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-book-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/book-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-cart-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/cart-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter


            - id: front-auth-logout
              uri: lb://4vidia-auth
              predicates:
                - Path=/api/v1/auth/auth/logout
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-auth
              uri: lb://4vidia-auth
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=3
                - name: NotJwtAuthorizationHeaderFilter

server:
  port: 8080

eureka:
  instance:
    # (선택) 게이트웨이 자신도 10초마다 생존 신고
    lease-renewal-interval-in-seconds: 10
  client:
    # ★ 필수: 5초마다 유레카 서버 명단을 새로고침 (기본 30초 -> 5초)
    registry-fetch-interval-seconds: 5

    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/
auth:
  cookie:
    secure: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always