spring:
  application:
    name: 4vidia-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: 4vidia-coupon-service
              uri: lb://4vidia-coupon-service
              predicates:
                - Path=/api/v1/coupon/**
              filters:
                - StripPrefix=3

            - id: 4vidia-user-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/user-service/**
              filters:
                - StripPrefix=3

            - id: 4vidia-test-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/bookstore-service/**
              filters:
                - StripPrefix=3

            - id: 4vidia-order-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/order-service/**
              filters:
                - StripPrefix=3

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/

auth:
  cookie:
    secure: true