spring:
  application:
    name: 4vidia-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: 4vidia-coupon-service
              uri: lb://4vidia-coupon-service
              predicates:
                - Path=/api/v1/coupon-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-user-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/user-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-order-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/order-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-book-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/book-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter

            - id: 4vidia-cart-service
              uri: lb://4vidia-bookstore-service
              predicates:
                - Path=/api/v1/cart-service/**
              filters:
                - StripPrefix=3
                - name: JwtAuthorizationHeaderFilter


            - id: front-auth-logout
              uri: lb://4vidia-auth
              predicates:
                - Path=/api/v1/auth/auth/logout
              filters:
                - name: JwtAuthorizationHeaderFilter
                - StripPrefix=3

            - id: 4vidia-auth-validate
              uri: lb://4vidia-auth
              predicates:
                - Path=/api/v1/auth/validate
              filters:
                - StripPrefix=3


            - id: 4vidia-auth-payco
              uri: lb://4vidia-auth
              predicates:
                - Path=/login/oauth2/code/**


            - id: 4vidia-auth
              uri: lb://4vidia-auth
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=3


server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/

auth:
  cookie:
    secure: true